### ISSUE TITLE
Can't Import Channel

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/bake#17]
**Describe the bug**

When I run the import command I receive an error

```bash
$ bake channel import reichwingwatch youtube https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg
Using config file: /Users/dirkkelly/.bake.yml
2019/05/07 18:21:56 Importing https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg...
2019/05/07 18:21:56 Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context
panic: Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context

goroutine 1 [running]:
log.Panicf(0x15aa1f1, 0x24, 0xc00012f8b0, 0x1, 0x1)
	/usr/local/opt/go/libexec/src/log/log.go:333 +0xda
github.com/breadtubetv/bake/util.LoadChannels(0xc0000b8940, 0x3a, 0x2)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/util/channel.go:258 +0x369
github.com/breadtubetv/bake/providers.importChannel(0x7ffeefbff32c, 0xe, 0xc0000e4380, 0xc000098630, 0x2c)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/providers/youtube.go:156 +0xbb
github.com/breadtubetv/bake/cmd.glob..func3(0x198a620, 0xc0000959b0, 0x3, 0x3)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/cmd/import.go:37 +0x302
github.com/spf13/cobra.(*Command).execute(0x198a620, 0xc0000958f0, 0x3, 0x3, 0x198a620, 0xc0000958f0)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x198a880, 0x0, 0x0, 0x0)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x198a880, 0x10074e0, 0xc000086058)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/breadtubetv/bake/cmd.Execute()
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/cmd/root.go:43 +0x2d
main.main()
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/main.go:8 +0x20
```

**To Reproduce**

```bash
cd breadtubetv/bake
git fetch origin
git reset origin/master --hard
go build
go install

cd breadtubetv/breadtubetv
bake channel import jaydeeforrester youtube https://www.youtube.com/channel/UCu_cKiCDa7qYhBptHALvFVw
```

**Expected behavior**

The channel would be imported created

**Additional context**

I have tried to reauth and that hasn't fixed it

```bash
$ bake config youtube
Using config file: /Users/dirkkelly/.bake.yml
Trying to get token from web
Your browser has been opened to an authorization URL.  This program will resume once authorization has been provided.
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=660935947237-ajqve9kv3n0nnhonhnc5j638fsfan31o.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8090&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.readonly&state=state-token
trying to save token
Saving credential file to: /Users/dirkkelly/.credentials/youtube-go.json
2019/05/07 18:24:21 Successfully authenticated and cached credentials.
```

Can confirm the error is being raised in `util/channel.go:258`

```go
		err = yaml.Unmarshal([]byte(data), &channel)
		if err != nil {
			log.Panicf("Error unmarshalling into channel: %v", err)
		}
```

- Can also confirm that I am still receiving this issue on older commits of bake

```
$ git reset b839a38b91e84d7eaef81d97bcc27f5273637763 --hard
HEAD is now at b839a38 refactor CreateChannelVideoFolder

$ go clean
$ go build
$ go install
```

```bash
$ bake channel import reichwingwatch youtube https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg
Using config file: /Users/dirkkelly/.bake.yml
2019/05/07 18:28:02 Importing https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg...
2019/05/07 18:28:02 Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context
panic: Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context
```

```bash
$ go run main.go channel import reichwingwatch youtube https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg
Using config file: /Users/dirkkelly/.bake.yml
2019/05/07 18:29:26 Importing https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg...
2019/05/07 18:29:26 Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context
panic: Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context
```

- Could it be that the json format from Google has changed?

- This is blocking me from processing suggestions

**Comment by jmickey** [comment]
It's working for me if I run via `go run main.go ...`. Will continue to investigate.

**Comment by dirkkelly** [comment]
Righto, if you can't reproduce it must be something with my install.

I tried your recommendation but no good with either raw command or the built binary.

```bash
$ go clean -i
$ go install

$ go run main.go channel import reichwingwatch youtube https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg
Using config file: /Users/dirkkelly/.bake.yml
2019/05/07 19:35:40 Importing https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg...
2019/05/07 19:35:40 Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context
panic: Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context

goroutine 1 [running]:
log.Panicf(0x15aa3f9, 0x24, 0xc00013d8b0, 0x1, 0x1)
	/usr/local/opt/go/libexec/src/log/log.go:333 +0xda
github.com/breadtubetv/bake/util.LoadChannels(0xc0000b6940, 0x3a, 0x2)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/util/channel.go:258 +0x369
github.com/breadtubetv/bake/providers.importChannel(0x7ffeefbff608, 0xe, 0xc0000f2380, 0xc0000a8570, 0x2c)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/providers/youtube.go:156 +0xbb
github.com/breadtubetv/bake/cmd.glob..func3(0x198a620, 0xc0000a59b0, 0x3, 0x3)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/cmd/import.go:37 +0x302
github.com/spf13/cobra.(*Command).execute(0x198a620, 0xc0000a58f0, 0x3, 0x3, 0x198a620, 0xc0000a58f0)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x198a880, 0x0, 0x0, 0x0)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x198a880, 0x10074e0, 0xc000096058)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/breadtubetv/bake/cmd.Execute()
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/cmd/root.go:43 +0x2d
main.main()
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/main.go:8 +0x20
exit status 2

$ bake channel import reichwingwatch youtube https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg
Using config file: /Users/dirkkelly/.bake.yml
2019/05/07 19:36:35 Importing https://www.youtube.com/channel/UCqNWJOeBOBSF1pm9tjGnKhg...
2019/05/07 19:36:35 Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context
panic: Error unmarshalling into channel: yaml: line 32: mapping values are not allowed in this context

goroutine 1 [running]:
log.Panicf(0x15aa3f9, 0x24, 0xc0001278b0, 0x1, 0x1)
	/usr/local/opt/go/libexec/src/log/log.go:333 +0xda
github.com/breadtubetv/bake/util.LoadChannels(0xc0000a0940, 0x3a, 0x2)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/util/channel.go:258 +0x369
github.com/breadtubetv/bake/providers.importChannel(0x7ffeefbff5fc, 0xe, 0xc0000dc380, 0xc000092570, 0x2c)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/providers/youtube.go:156 +0xbb
github.com/breadtubetv/bake/cmd.glob..func3(0x198a620, 0xc00008f9b0, 0x3, 0x3)
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/cmd/import.go:37 +0x302
github.com/spf13/cobra.(*Command).execute(0x198a620, 0xc00008f8f0, 0x3, 0x3, 0x198a620, 0xc00008f8f0)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x198a880, 0x0, 0x0, 0x0)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x198a880, 0x10074e0, 0xc000080058)
	/Users/dirkkelly/.go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/breadtubetv/bake/cmd.Execute()
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/cmd/root.go:43 +0x2d
main.main()
	/Users/dirkkelly/.go/src/github.com/breadtubetv/bake/main.go:8 +0x20
```

Will see if I can resolve tomorrow.

Thanks
